# Generated by Django 4.0.1 on 2022-01-06 19:31

from django.db import migrations, models
import profile_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(upload_to='static/images/profile_img', validators=[profile_app.validators.validate_file_size]),
        ),
    ]
