# Generated by Django 4.0.1 on 2022-01-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profilemodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='sahrif',
            new_name='sharif',
        ),
    ]
