# Generated by Django 4.0.1 on 2022-01-07 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile_app.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0003_rename_sahrif_profilemodel_sharif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30, null=True)),
                ('familya', models.CharField(max_length=35, null=True)),
                ('sharif', models.CharField(max_length=35, null=True)),
                ('image', models.ImageField(upload_to='static/images/profile_img', validators=[profile_app.validators.validate_file_size])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_information',
                'verbose_name_plural': 'User_informations',
            },
        ),
    ]
