# Generated by Django 4.0.1 on 2022-01-07 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0004_alter_profilemodel_user_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='jcpYqyEF', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sended_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Code which is sended to user's email",
                'verbose_name_plural': "Codes which is sended to users's emails",
            },
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Users information', 'verbose_name_plural': 'Users informations'},
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
