# Generated by Django 4.0.1 on 2022-01-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0018_alter_emailcode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcode',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='code',
            field=models.CharField(default='jIfgY1C1', max_length=8),
        ),
    ]
