# Generated by Django 4.0.1 on 2022-01-08 10:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KursModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('position', models.PositiveIntegerField(help_text='qayerda kelishini korsating Masalan: 1 yoki 5 orinda kelsin', verbose_name='Positsiyasi')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Tugatildi', 'Tugatildi'), ('Failing', 'Failing')], default='Active', max_length=9)),
                ('addet_at', models.DateTimeField(auto_now_add=True, verbose_name='Model qoshilgan vaqt')),
                ('kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models1.kursmodel', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Asosiy Model',
                'verbose_name_plural': 'Asosiy Modellar',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time_limit', models.IntegerField(choices=[(0, 0), (10, 10), (20, 20), (30, 30), (40, 40), (60, 60), (90, 90)], default=0, help_text='Agar testni vaqtini cheklamoqchi bolsangis quyiydagilardan birini tanlang!', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Qoshilgan vaqti')),
                ('m_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.mainmodel')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(null=True)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.testmodel')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='InsideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('document', models.FileField(blank=True, help_text='Documentlar yuklash uchun( .docx, .txt, .pptx ...', null=True, upload_to='static/documents')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='static/videos', verbose_name='videos')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('m_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.mainmodel', verbose_name='Qoshmoqchi bolgan malumotingiz modelini tanlang')),
            ],
            options={
                'verbose_name': 'Model uchun malumot(content, video, file...)',
                'verbose_name_plural': 'Model uchun malumot(content, video, file...)lar',
            },
        ),
        migrations.CreateModel(
            name='DescriptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='static/Models/images')),
                ('added_at', models.DateTimeField()),
                ('m_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.mainmodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Model uchun description',
                'verbose_name_plural': 'Model uchun descriptionlar',
            },
        ),
        migrations.CreateModel(
            name='DesContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True)),
                ('content', ckeditor.fields.RichTextField(null=True, verbose_name='Conent')),
                ('des', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.descriptmodel', verbose_name='Description Model')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', ckeditor.fields.RichTextField(null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.questionmodel', verbose_name='Question')),
            ],
        ),
    ]
