# Generated by Django 4.0.1 on 2022-01-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models1', '0002_remove_insidemodel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_link',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
