# Generated by Django 4.0.1 on 2022-01-09 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models1', '0004_alter_descriptmodel_m_id_alter_filemodel_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='position',
        ),
        migrations.AlterField(
            model_name='insidemodel',
            name='m_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.mainmodel', verbose_name='Qoshmoqchi bolgan malumotingiz modulini tanlang'),
        ),
        migrations.AlterField(
            model_name='insidemodel',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Bajarilmoqda', 'Bajarilmoqda'), ('Tugatildi', 'Tugatildi'), ('Failing', 'Failing')], default='Active', max_length=15),
        ),
        migrations.CreateModel(
            name='Korishlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.mainmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Korishlar',
                'verbose_name_plural': 'Korishlar',
            },
        ),
        migrations.CreateModel(
            name='FModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Content', 'Content'), ('Prezintatsiya', 'Prezintatsiya'), ('Document', 'Document'), ('Video', 'Video')], max_length=24, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('inside_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.insidemodel')),
            ],
            options={
                'verbose_name': 'Sinov Ishi',
            },
        ),
    ]
