# Generated by Django 4.0.1 on 2022-01-09 10:48

from django.db import migrations, models
import models1.extentions


class Migration(migrations.Migration):

    dependencies = [
        ('models1', '0005_remove_filemodel_position_alter_insidemodel_m_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='position',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fmodel',
            name='file',
            field=models.FileField(null=True, upload_to='files/', validators=[models1.extentions.video_validate_file_extension]),
        ),
    ]
