# Generated by Django 4.0.1 on 2022-01-09 11:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models1', '0008_inlinemodelcontent_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemodel',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='inlinemodelcontent',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
        migrations.AlterField(
            model_name='inlinemodelcontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
