# Generated by Django 4.0.1 on 2022-01-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models1', '0009_alter_filemodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmodel',
            name='inside_model',
        ),
        migrations.RemoveField(
            model_name='korishlar',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='korishlar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='m_id',
        ),
        migrations.DeleteModel(
            name='AnswerModel',
        ),
        migrations.DeleteModel(
            name='FModel',
        ),
        migrations.DeleteModel(
            name='Korishlar',
        ),
        migrations.DeleteModel(
            name='QuestionModel',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
