# Generated by Django 4.0.1 on 2022-01-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models1', '0010_remove_fmodel_inside_model_remove_korishlar_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='downloadablbe',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
