# Generated by Django 4.0.1 on 2022-01-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models1', '0011_filemodel_downloadablbe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='downloadablbe',
            new_name='downloadable',
        ),
    ]
