# Generated by Django 4.0.1 on 2022-01-10 09:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models1', '0012_rename_downloadablbe_filemodel_downloadable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(blank=True, help_text='Documentlar kiriting', upload_to='static/documents/files')),
                ('downloadable', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='downloadable',
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_type',
            field=models.CharField(choices=[('Prezintatsiya', 'Prezintatsiya'), ('Video', 'Video')], help_text='File turini tanlang', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('inside_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.insidemodel')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documnets',
            },
        ),
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('document_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.insidemodel', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
            },
        ),
    ]
