# Generated by Django 4.0.1 on 2022-01-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models1', '0013_documentfile_remove_filemodel_downloadable_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='DOCMODELS',
        ),
        migrations.AddField(
            model_name='documentfile',
            name='document_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models1.docmodels', verbose_name='Document'),
        ),
    ]
