# Generated by Django 4.0.1 on 2022-01-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models1', '0015_remove_documentcontent_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='downloadable',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
